import { Video, Channel } from './types'

export const mockVideos: Video[] = [
  {
    id: '1',
    title: 'Stream de 8 horas seguidas',
    thumbnail: 'https://picsum.photos/seed/v1/507/285',
    duration: '8:24:11',
    channelName: 'tteuw',
    channelAvatar: 'https://picsum.photos/seed/ch1/37/37',
    channelSlug: 'tteuw',
    isExclusive: true,
    views: 12400,
    createdAt: '2026-03-10',
  },
  {
    id: '2',
    title: 'Ranked até o limite',
    thumbnail: 'https://picsum.photos/seed/v2/507/285',
    duration: '3:10:00',
    channelName: 'brkk',
    channelAvatar: 'https://picsum.photos/seed/ch2/37/37',
    channelSlug: 'brkk',
    isExclusive: false,
    views: 8900,
    createdAt: '2026-03-12',
  },
  {
    id: '3',
    title: 'Jogando com inscritos ao vivo',
    thumbnail: 'https://picsum.photos/seed/v3/507/285',
    duration: '2:45:30',
    channelName: 'coringa',
    channelAvatar: 'https://picsum.photos/seed/ch3/37/37',
    channelSlug: 'coringa',
    isExclusive: true,
    views: 5600,
    createdAt: '2026-03-15',
  },
  {
    id: '4',
    title: 'Gameplay noturno',
    thumbnail: 'https://picsum.photos/seed/v4/376/211',
    duration: '1:30:00',
    channelName: 'tteuw',
    channelAvatar: 'https://picsum.photos/seed/ch1/37/37',
    channelSlug: 'tteuw',
    isExclusive: false,
    views: 3200,
    createdAt: '2026-03-18',
  },
  {
    id: '5',
    title: 'Torneio especial',
    thumbnail: 'https://picsum.photos/seed/v5/376/211',
    duration: '4:00:00',
    channelName: 'brkk',
    channelAvatar: 'https://picsum.photos/seed/ch2/37/37',
    channelSlug: 'brkk',
    isExclusive: true,
    views: 7100,
    createdAt: '2026-03-19',
  },
  {
    id: '6',
    title: 'Late night chill',
    thumbnail: 'https://picsum.photos/seed/v6/376/211',
    duration: '2:00:00',
    channelName: 'coringa',
    channelAvatar: 'https://picsum.photos/seed/ch3/37/37',
    channelSlug: 'coringa',
    isExclusive: false,
    views: 2800,
    createdAt: '2026-03-20',
  },
  {
    id: '7',
    title: 'Especial fim de semana',
    thumbnail: 'https://picsum.photos/seed/v7/376/211',
    duration: '5:30:00',
    channelName: 'tteuw',
    channelAvatar: 'https://picsum.photos/seed/ch1/37/37',
    channelSlug: 'tteuw',
    isExclusive: true,
    views: 9900,
    createdAt: '2026-03-21',
  },
]

export const mockChannels: Channel[] = [
  { id: '1', name: 'tteuw', username: '@tteuw', avatar: 'https://picsum.photos/seed/ch1/64/64', description: 'Streamer competitivo', videoCount: 200, isSubscribed: false, isFollowing: false },
  { id: '2', name: 'brkk', username: '@brkk', avatar: 'https://picsum.photos/seed/ch2/64/64', description: 'FPS e estratégia', videoCount: 145, isSubscribed: false, isFollowing: false },
  { id: '3', name: 'coringa', username: '@coringa', avatar: 'https://picsum.photos/seed/ch3/64/64', description: 'Entretenimento geral', videoCount: 312, isSubscribed: false, isFollowing: false },
  { id: '4', name: 'xablau', username: '@xablau', avatar: 'https://picsum.photos/seed/ch4/64/64', description: 'RPG e aventura', videoCount: 89, isSubscribed: false, isFollowing: false },
  { id: '5', name: 'kauan_plays', username: '@kauan_plays', avatar: 'https://picsum.photos/seed/ch5/64/64', description: 'Esports', videoCount: 201, isSubscribed: false, isFollowing: false },
  { id: '6', name: 'ninas_gamer', username: '@ninas_gamer', avatar: 'https://picsum.photos/seed/ch6/64/64', description: 'Variety', videoCount: 76, isSubscribed: false, isFollowing: false },
  { id: '7', name: 'pro_zeca', username: '@pro_zeca', avatar: 'https://picsum.photos/seed/ch7/64/64', description: 'Competitivo', videoCount: 430, isSubscribed: false, isFollowing: false },
  { id: '8', name: 'lili_stream', username: '@lili_stream', avatar: 'https://picsum.photos/seed/ch8/64/64', description: 'Cozy gaming', videoCount: 119, isSubscribed: false, isFollowing: false },
  { id: '9', name: 'dark_wolf', username: '@dark_wolf', avatar: 'https://picsum.photos/seed/ch9/64/64', description: 'Horror games', videoCount: 55, isSubscribed: false, isFollowing: false },
  { id: '10', name: 'rapido_br', username: '@rapido_br', avatar: 'https://picsum.photos/seed/ch10/64/64', description: 'Speedruns', videoCount: 88, isSubscribed: false, isFollowing: false },
]
